name: self_hosted_cicd
description: A selfhosted Flutter CICD project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  freezed_annotation: 2.2.0
  freezed: 2.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: 2.3.2
  flutter_lints: 2.0.0


flutter:
  assets:
    - config/
  uses-material-design: true
